### ISSUE TITLE
Blosclz performance tuning on X86

### ISSUE THREAD

**Issue by littlezhou** [Blosc/c-blosc#97] opened 2015-03-29 16:05 UTC
Hi, I'm very interesting in blosclz compress/decompress algorithm and want to make it run faster on x86 processor(by taking advantage of features of X86), any suggestions on this? I've tried to use AVX2 instruction set instead of SSE in shuffle and unshuffle functions and there are about ~40% performance improvement compared to SSE. Thanks!

**Comment by esc** [comment] 2015-03-29 16:25
Just a quick note about terminology. Blosc is a metacodec, this means it takes care of shuffling and multithreading. The real compression is done by other codecs of which blosclz is one.

Anyway, regarding the shuffling, please do show us your code so that we can get an idea of what you have done and also so that we may run the benchmarks ourselves. Speed improvements are *always* interesting! :-D

**Comment by littlezhou** [comment] 2015-03-30 17:03
A pull request has been created for you to evaluate. Even though AVX2 shuffle shows 40% improvement over SSE2 in standalone tests, but SSE2 Shuffle (unshuffle) operation consumes only a little time (less than 8%) compared to the total time need for blosc compress (decompress) test, so almost no performance improvement can be seen from bench testing. :(

**Comment by FrancescAlted** [comment] 2015-04-19 11:10
Hi @littlezhou .  I have just merged your PR #99 but unfortunately, after I tried on a machine with AVX2, it does not pass the test suite:

```
$ make test
Running tests...
Test project /home/francesc/c-blosc/build
      Start  1: test_test_api
 1/12 Test  #1: test_test_api ....................   Passed    0.01 sec
      Start  2: test_test_basics
 2/12 Test  #2: test_test_basics .................***Failed    0.01 sec
      Start  3: test_blosclz_1
 3/12 Test  #3: test_blosclz_1 ...................   Passed    5.26 sec
      Start  4: test_lz4_1
^CMakefile:136: recipe for target 'test' failed
make: *** [test] Interrupt
```

(but of course this goes well with a non AVX2 machine)

I think the problem in 'tests/tests_basics.c' is that we cannot assume that users are passing buffers that are aligned to 32 bytes (256 bits) for maximum performance in AVX2.  I have tried to relax this condition in rev f4a2ef6, but apparently this is not enough.

Could you please have a look at that?  Thanks!

**Comment by littlezhou** [comment] 2015-04-20 08:29
I'll have a look at this, Sorry for the problem.

**Comment by FrancescAlted** [comment] 2015-04-20 11:47
By doing some debugging, it seems that the problem is only in `shuffle16_AVX2`, which is not that bad :)

**Comment by littlezhou** [comment] 2015-04-20 12:11
In fact it may impact all the functions. 
In shuffle and unshuffle functions, the following check:
  int multiple_of_block = (blocksize % (16 * bytesoftype)) == 0
It should be 32 instead of 16.

**Comment by littlezhou** [comment] 2015-04-20 12:17
That's really a critical bug, Really sorry for that! :(

**Comment by FrancescAlted** [comment] 2015-04-20 13:04
I tried that, but it does not fix the problem.

**Comment by littlezhou** [comment] 2015-04-20 13:18
That's strange! It works for me, you can have a try on my repo.

**Comment by FrancescAlted** [comment] 2015-04-20 14:10
Yep, it works.  I changed the value to the SSE2 versions not AVX2 ones.

Also, looking at you branch, you added this change:

```
-       if(blocksize >= 512)
-               shuffle16_AVX2(_dest, _src, blocksize);
-       else
-               _shuffle(bytesoftype, blocksize, _src, _dest);
+    shuffle16_AVX2(_dest, _src, blocksize);
```

What was the purpose of the original code?

**Comment by littlezhou** [comment] 2015-04-20 14:25
I was doing some testing then and forgot to delete it....

**Comment by FrancescAlted** [comment] 2015-04-20 14:31
I see.  Added your version in rev 6f4c01d.  Closing and thank you very much for you speedy response!

**Closed by FrancescAlted** 2015-04-20 14:31 UTC

**Comment by littlezhou** [comment] 2015-04-20 14:37
Thank you very much!

**Comment by FrancescAlted** [comment] 2015-04-20 14:39
BTW, would you mind providing your actual name?  I would like to properly give credit to you in docs.
