### ISSUE TITLE
zstd 1.1.4 vs zstd 1.1.3, more slow

### ISSUE THREAD

**Issue by Portiella** [Blosc/c-blosc#200] opened 2017-07-18 13:21 UTC
Hi,

I have detected that zstd 1.1.4 (c-blosc 1.11.3) is a bit slower than 1.1.3 (c-blosc 1.12.0)

It's possible?

**Comment by FrancescAlted** [comment] 2017-07-19 08:58
Uh, you possibly mean zstd 1.1.4 (c-blosc 1.11.3) slower than zstd 1.3.0 (c-blosc 1.12.0), right?
Well, I hope so, because zstd is constantly *improving* ;) 

Closing this.  In case there is an actual regression, please re-open and specify some actual figures.

**Closed by FrancescAlted** 2017-07-19 08:58 UTC
