### ISSUE TITLE
Blosc 1.6.1 fails to build on PPC G4, OS X 10.5.8

### ISSUE THREAD

**Issue by zzanderr** [Blosc/c-blosc#117] opened 2015-05-07 21:22 UTC
I am using Macports to install most of my personal software built from source.  The first (install) build of Blosc I used was  v1.5.2, and have upgraded with no trouble through Blosc v1.6.0.  Blosc v1.6.1 fails.
GCC 4.2 (Apple's version) tries to compile  shuffle-sse2.c which, of course, is not needed, and cannot be compiled on a PowerPC. I am attaching a PNG of the fail point in the build:

![failpoint](https://cloud.githubusercontent.com/assets/12305296/7526182/284f2698-f4d5-11e4-80b9-db31f08b71a9.png)

I realize that making sure code compiles on a PPC G4 is not your top priority, but if you can find the time your help would be appreciated!

**Comment by zzanderr** [comment] 2015-05-07 22:00
I forgot to mention that a ticket has been filed with MacPorts: 
https://trac.macports.org/ticket/47658
You will find the full build log there.

**Comment by jack-pappas** [comment] 2015-05-10 14:54
@zzanderr Would you mind pulling the latest sources from ``master`` and trying to build again? This build failure is likely caused by my changes in #108 but should be fixed by #116.

**Comment by zzanderr** [comment] 2015-05-13 00:10
Yes, apparently that fixes it.  Thanks for your expertise (and apologies for responding so slowly)!

**Closed** 2015-05-20 07:46 UTC
